"""new model named Follow and followed and followers fields to user model

Revision ID: 39be9b14e45c
Revises: 5a980d5b90c3
Create Date: 2021-07-23 11:16:10.915191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39be9b14e45c'
down_revision = '5a980d5b90c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
