"""registered an event litner ofr markdown

Revision ID: 5a980d5b90c3
Revises: 3e4093311d39
Create Date: 2021-07-22 15:42:52.538941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a980d5b90c3'
down_revision = '3e4093311d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
